import { ScrollView, Text } from "react-native";

export function ScrollViewComponent (){
    return(
    <ScrollView>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
        <Text>Texto para ocupar a tela</Text>
    </ScrollView>
    );
}